# Generated by Django 3.1.2 on 2020-10-26 03:53

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_auto_20201026_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='city',
            field=models.CharField(default='N', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='state',
            field=localflavor.us.models.USStateField(default=('AL', 'Alabama'), max_length=2),
        ),
    ]
