# Generated by Django 3.1.2 on 2020-10-26 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_auto_20201026_0353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='state',
        ),
    ]
