# Generated by Django 3.1.2 on 2020-10-26 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=100)),
                ('text_decription', models.TextField()),
                ('min_age', models.IntegerField(default=18)),
                ('max_age', models.IntegerField(default=65)),
                ('salary', models.IntegerField()),
                ('location', localflavor.us.models.USStateField(blank=True, default=('AL', 'Alabama'), max_length=2, null=True)),
                ('n_openings', models.IntegerField(default=0)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
