# Generated by Django 3.1.2 on 2020-10-26 03:53

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201026_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='state',
            field=localflavor.us.models.USStateField(default=('AL', 'Alabama'), max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_decription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
