# Generated by Django 3.1.2 on 2020-10-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201024_0520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(default='Nan', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='salary',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
