# Generated by Django 3.1.2 on 2020-10-24 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201024_1906'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
