# Generated by Django 3.1.2 on 2020-10-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='job_title',
            new_name='position_name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='text_decription',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comparny_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
        migrations.AddField(
            model_name='post',
            name='max_age',
            field=models.IntegerField(default=65),
        ),
        migrations.AddField(
            model_name='post',
            name='min_age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='post',
            name='n_openings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
