# Generated by Django 3.1.2 on 2020-10-25 15:19

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=localflavor.us.models.USStateField(max_length=2),
        ),
    ]
